name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable:
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    uses: zylos-platform/zylos-service-parent/.github/workflows/reusable-build-and-publish.yaml@main
    with:
      service-name: zylos-hello-service
      java-version: "25"
      coverage-threshold: "0.70"
      open-deploy-pr: true
    secrets:
      BOOTSTRAP_REPO_TOKEN: ${{ secrets.BOOTSTRAP_REPO_TOKEN }}
